/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookmanager;

import static bookmanager.newMain.setBackup;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author medit
 */
public class records extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    ArrayList<record> recs = new ArrayList();

    public records() {

        initComponents();
        rreading.setSelected(true);
        dtm.setColumnIdentifiers(new Object[]{"Name", "Writer", "Publisher", "Type", "Issue", "Year", "Topic", "Shelf", "Shelf no"});
        table.setModel(dtm);
        rprimary.setSelected(true);

    }

    /**
     * Creates new form main
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        publisher = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        writer = new javax.swing.JTextField();
        lname = new javax.swing.JLabel();
        lpublisher = new javax.swing.JLabel();
        lwriter = new javax.swing.JLabel();
        ltype = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rreading = new javax.swing.JRadioButton();
        rstudy = new javax.swing.JRadioButton();
        rmagazine = new javax.swing.JRadioButton();
        rprimary = new javax.swing.JRadioButton();
        rsecondary = new javax.swing.JRadioButton();
        issue = new javax.swing.JTextField();
        lissue = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        lyear = new javax.swing.JLabel();
        ltopic = new javax.swing.JLabel();
        topic = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        addtable = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        shelfno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please enter the details of the book");

        lname.setText("Name");

        lpublisher.setText("Publisher");

        lwriter.setText("Writer");

        ltype.setText("Type");

        jLabel7.setText("Kind :");

        add.setText("Add the books the database");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel8.setText("Shelf :");

        buttonGroup1.add(rreading);
        rreading.setText("Reading");
        rreading.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rreadingStateChanged(evt);
            }
        });

        buttonGroup1.add(rstudy);
        rstudy.setText("Study");
        rstudy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rstudyStateChanged(evt);
            }
        });

        buttonGroup1.add(rmagazine);
        rmagazine.setText("Magazine");
        rmagazine.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rmagazineStateChanged(evt);
            }
        });

        buttonGroup2.add(rprimary);
        rprimary.setText("Primary Shelf");

        buttonGroup2.add(rsecondary);
        rsecondary.setText("Secondary Shelf");

        issue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                issueKeyReleased(evt);
            }
        });

        lissue.setText("Issue");

        year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearKeyReleased(evt);
            }
        });

        lyear.setText("year");

        ltopic.setText("topic");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        addtable.setText("Add to table");
        addtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtableActionPerformed(evt);
            }
        });

        delete.setText("Delete from table");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        shelfno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                shelfnoKeyReleased(evt);
            }
        });

        jLabel2.setText("Shelf No");

        jButton1.setText("Close this screen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lname)
                            .addComponent(lyear)
                            .addComponent(ltopic)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lpublisher, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ltype))
                            .addComponent(lwriter)
                            .addComponent(lissue)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(year, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(issue, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(publisher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(writer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(topic)
                                    .addComponent(shelfno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(279, 279, 279)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(rreading)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(rstudy)))
                                                .addGap(18, 18, 18)
                                                .addComponent(rmagazine)
                                                .addGap(69, 69, 69))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rprimary)
                                                .addGap(37, 37, 37)
                                                .addComponent(rsecondary)
                                                .addGap(62, 62, 62))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(addtable)
                                        .addGap(31, 31, 31)
                                        .addComponent(delete)
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(501, 501, 501)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(47, 47, 47))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rreading)
                            .addComponent(rstudy)
                            .addComponent(rmagazine))
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rprimary)
                            .addComponent(rsecondary))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addtable)
                            .addComponent(delete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lpublisher))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltype, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(writer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lwriter))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lissue))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lyear))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltopic))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shelfno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rreadingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rreadingStateChanged
        if (rreading.isSelected()) {
            year.setEditable(false);
            issue.setEditable(false);
            topic.setEditable(false);
            writer.setEditable(true);
            issue.setText("");
            year.setText("");
            topic.setText("");
        }
    }//GEN-LAST:event_rreadingStateChanged

    private void rstudyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rstudyStateChanged
        if (rstudy.isSelected()) {

            year.setEditable(false);
            issue.setEditable(false);
            topic.setEditable(true);
            writer.setEditable(false);
            writer.setText("");
            issue.setText("");
            year.setText("");
        }
    }//GEN-LAST:event_rstudyStateChanged

    private void rmagazineStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rmagazineStateChanged
        if (rmagazine.isSelected()) {
            year.setEditable(true);
            issue.setEditable(true);
            topic.setEditable(false);
            writer.setEditable(false);
            writer.setText("");
            topic.setText("");
        }
    }//GEN-LAST:event_rmagazineStateChanged

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
  
        int rowi = 0;
        for (record rec : recs) {
            if (dtm.getValueAt(rowi, 7).toString().equals("Primary Shelf")) {
                mainshelf m = new mainshelf();
                rec.addRecord();
                int i = m.addSelf(rec, Integer.parseInt(dtm.getValueAt(rowi, 8).toString()));

            } else {
                auxshelf m = new auxshelf();
                rec.addRecord();
                int i = m.addSelf(rec, Integer.parseInt(dtm.getValueAt(rowi, 8).toString()));
                System.out.println(i);

            }
            rowi++;
        }

        recs.clear();
        dtm.setRowCount(0);

    }//GEN-LAST:event_addActionPerformed

    private void addtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtableActionPerformed

        if (rreading.isSelected()) {
            if (writer.getText().equals("") || publisher.getText().equals("") || type.getText().equals("") || name.getText().equals("") || shelfno.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "You should fill all the required fields", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            reading read = new reading();
            read.name = name.getText();
            read.publisher = publisher.getText();
            read.type = type.getText();
            read.writer = writer.getText();
            if (rprimary.isSelected()) {
                dtm.addRow(read.returnVar(rprimary.getText(), Integer.parseInt(shelfno.getText())));
                recs.add(read);
            } else {
                dtm.addRow(read.returnVar(rsecondary.getText(), Integer.parseInt(shelfno.getText())));
                recs.add(read);
            }

        }
        if (rstudy.isSelected()) {
            if (topic.getText().equals("") || publisher.getText().equals("") || type.getText().equals("") || name.getText().equals("") || shelfno.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "You should fill all the required fields", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            study stu = new study();
            stu.name = name.getText();
            stu.publisher = publisher.getText();
            stu.type = type.getText();
            stu.topic = topic.getText();
            if (rprimary.isSelected()) {
                dtm.addRow(stu.returnVar(rprimary.getText(), Integer.parseInt(shelfno.getText())));
                recs.add(stu);
            } else {
                dtm.addRow(stu.returnVar(rsecondary.getText(), Integer.parseInt(shelfno.getText())));
                recs.add(stu);
            }
        }
        if (rmagazine.isSelected()) {
            if (issue.getText().equals("") || publisher.getText().equals("") || type.getText().equals("") || name.getText().equals("") || shelfno.getText().equals("") || year.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "You should fill all the required fields", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            magazine mg = new magazine();
            mg.name = name.getText();
            mg.publisher = publisher.getText();
            mg.type = type.getText();
            mg.issue = Integer.parseInt(issue.getText());
            mg.year = Integer.parseInt(year.getText());
            if (rprimary.isSelected()) {
                dtm.addRow(mg.returnVar(rprimary.getText(), Integer.parseInt(shelfno.getText())));
                recs.add(mg);
            } else {
                dtm.addRow(mg.returnVar(rsecondary.getText(), Integer.parseInt(shelfno.getText())));
                recs.add(mg);
            }
        }
    }//GEN-LAST:event_addtableActionPerformed

    private void issueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issueKeyReleased
        char[] a = issue.getText().toCharArray();
        int sayac = 0;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < a.length; i++) {
            if (Character.isLetter(a[i])) {

                if (sayac == 0) {
                    sayac++;
                    JOptionPane.showMessageDialog(rootPane, "Issue field cannot take a character", "Error", JOptionPane.WARNING_MESSAGE);

                }

            } else {
                sb.append(a[i]);
            }
            issue.setText(String.valueOf(sb));
        }
    }//GEN-LAST:event_issueKeyReleased

    private void yearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyReleased
        char[] a = year.getText().toCharArray();
        int sayac = 0;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < a.length; i++) {
            if (Character.isLetter(a[i])) {

                if (sayac == 0) {
                    sayac++;
                    JOptionPane.showMessageDialog(rootPane, "Year field cannot take a character", "Error", JOptionPane.WARNING_MESSAGE);

                }

            } else {
                sb.append(a[i]);
            }
            year.setText(String.valueOf(sb));
        }
    }//GEN-LAST:event_yearKeyReleased

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        record r = ((record) table.getValueAt(table.getSelectedRow(), 0));
        recs.remove(r);
        dtm.removeRow(table.getSelectedRow());
    }//GEN-LAST:event_deleteActionPerformed

    private void shelfnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_shelfnoKeyReleased
        char[] a = shelfno.getText().toCharArray();
        int sayac = 0;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < a.length; i++) {
            if (Character.isLetter(a[i])) {

                if (sayac == 0) {
                    sayac++;
                    JOptionPane.showMessageDialog(rootPane, "Shelf no field cannot take a character", "Error", JOptionPane.WARNING_MESSAGE);

                }

            } else {
                sb.append(a[i]);
            }
            shelfno.setText(String.valueOf(sb));
        }
    }//GEN-LAST:event_shelfnoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setTable() {
        String selected = "";
        if (rprimary.isSelected()) {
            selected = rprimary.getText();
        } else {
            selected = rsecondary.getText();
        }
        dtm.setRowCount(0);
        for (record rec : recs) {
            dtm.addRow(rec.returnVar(selected, Integer.parseInt(shelfno.getText())));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               records r= new records();
               r.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton addtable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton delete;
    private javax.swing.JTextField issue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lissue;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lpublisher;
    private javax.swing.JLabel ltopic;
    private javax.swing.JLabel ltype;
    private javax.swing.JLabel lwriter;
    private javax.swing.JLabel lyear;
    private javax.swing.JTextField name;
    private javax.swing.JTextField publisher;
    private javax.swing.JRadioButton rmagazine;
    private javax.swing.JRadioButton rprimary;
    private javax.swing.JRadioButton rreading;
    private javax.swing.JRadioButton rsecondary;
    private javax.swing.JRadioButton rstudy;
    private javax.swing.JTextField shelfno;
    private javax.swing.JTable table;
    private javax.swing.JTextField topic;
    private javax.swing.JTextField type;
    private javax.swing.JTextField writer;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
